// mycelix-workspace/observatory/src/lib/components/Toast.svelte
<script lang="ts">
  import { toasts } from '$lib/toast';

  const typeStyles: Record<string, string> = {
    success: 'bg-green-800 border-green-600 text-green-100',
    error: 'bg-red-800 border-red-600 text-red-100',
    info: 'bg-blue-800 border-blue-600 text-blue-100',
  };
</script>

{#if $toasts.length > 0}
  <div class="fixed top-4 right-4 z-[60] space-y-2 max-w-sm" aria-live="polite" aria-label="Notifications">
    {#each $toasts as toast (toast.id)}
      <div
        class="px-4 py-3 rounded-lg border shadow-lg text-sm flex items-start gap-2 animate-slide-in {typeStyles[toast.type] ?? typeStyles.info}"
        role="status"
      >
        <span class="flex-1">{toast.message}</span>
        <button
          on:click={() => toasts.dismiss(toast.id)}
          class="text-current opacity-60 hover:opacity-100 ml-2 shrink-0"
          aria-label="Dismiss notification"
        >
          &#x2715;
        </button>
      </div>
    {/each}
  </div>
{/if}

<style>
  @keyframes slideIn {
    from { transform: translateX(100%); opacity: 0; }
    to { transform: translateX(0); opacity: 1; }
  }
  :global(.animate-slide-in) {
    animation: slideIn 0.2s ease-out;
  }
</style>

// mycelix-mail/ui/frontend/src/components/Toast.tsx
import { useEffect, useState } from 'react';
import type { Toast as ToastType } from '@/store/toastStore';

interface ToastProps {
  toast: ToastType;
  onClose: () => void;
}

const toastStyles = {
  success: {
    bg: 'bg-green-50 dark:bg-green-900/30',
    border: 'border-green-500 dark:border-green-500',
    text: 'text-green-800 dark:text-green-200',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
      </svg>
    ),
  },
  error: {
    bg: 'bg-red-50 dark:bg-red-900/30',
    border: 'border-red-500 dark:border-red-500',
    text: 'text-red-800 dark:text-red-200',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M6 18L18 6M6 6l12 12"
        />
      </svg>
    ),
  },
  warning: {
    bg: 'bg-yellow-50 dark:bg-yellow-900/30',
    border: 'border-yellow-500 dark:border-yellow-500',
    text: 'text-yellow-800 dark:text-yellow-200',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
        />
      </svg>
    ),
  },
  info: {
    bg: 'bg-blue-50 dark:bg-blue-900/30',
    border: 'border-blue-500 dark:border-blue-500',
    text: 'text-blue-800 dark:text-blue-200',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
        />
      </svg>
    ),
  },
};

export default function Toast({ toast, onClose }: ToastProps) {
  const [isVisible, setIsVisible] = useState(false);
  const style = toastStyles[toast.type];

  useEffect(() => {
    // Trigger slide-in animation
    const timeout = setTimeout(() => setIsVisible(true), 10);
    return () => clearTimeout(timeout);
  }, []);

  const handleClose = () => {
    setIsVisible(false);
    setTimeout(onClose, 300); // Wait for slide-out animation
  };

  return (
    <div
      className={`
        flex items-start p-4 mb-3 rounded-lg border-l-4 shadow-lg
        ${style.bg} ${style.border} ${style.text}
        transform transition-all duration-300 ease-in-out
        ${isVisible ? 'translate-x-0 opacity-100' : 'translate-x-full opacity-0'}
        min-w-[300px] max-w-md
      `}
      role="alert"
    >
      <div className="flex-shrink-0">{style.icon}</div>
      <div className="ml-3 flex-1">
        <p className="text-sm font-medium">{toast.message}</p>
        {toast.action && (
          <button
            onClick={() => {
              toast.action!.onClick();
              handleClose();
            }}
            className="mt-2 text-sm font-semibold underline hover:no-underline focus:outline-none"
          >
            {toast.action.label}
          </button>
        )}
      </div>
      <button
        onClick={handleClose}
        className="ml-3 flex-shrink-0 inline-flex text-gray-400 hover:text-gray-500 dark:text-gray-500 dark:hover:text-gray-400 focus:outline-none"
        aria-label="Close"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  );
}
