// mycelix-praxis/apps/web/src/components/EmptyState.tsx
// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
/**
 * EmptyState Component
 *
 * Displays when no data is available with helpful messaging and call-to-action
 */

import React from 'react';

export interface EmptyStateProps {
  icon?: string;
  title: string;
  description: string;
  action?: {
    label: string;
    onClick: () => void;
  };
  secondaryAction?: {
    label: string;
    onClick: () => void;
  };
}

export const EmptyState: React.FC<EmptyStateProps> = ({
  icon = '📭',
  title,
  description,
  action,
  secondaryAction,
}) => {
  return (
    <div
      role="status"
      aria-label={title}
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '64px 24px',
        textAlign: 'center',
        backgroundColor: '#f9fafb',
        borderRadius: '12px',
        border: '2px dashed #e5e7eb',
      }}
    >
      {/* Icon */}
      <div
        aria-hidden="true"
        style={{
          fontSize: '64px',
          marginBottom: '24px',
          opacity: 0.8,
        }}
      >
        {icon}
      </div>

      {/* Title */}
      <h3
        style={{
          margin: '0 0 12px 0',
          fontSize: '20px',
          fontWeight: '600',
          color: '#111827',
        }}
      >
        {title}
      </h3>

      {/* Description */}
      <p
        style={{
          margin: '0 0 32px 0',
          fontSize: '15px',
          color: '#6b7280',
          maxWidth: '400px',
          lineHeight: '1.6',
        }}
      >
        {description}
      </p>

      {/* Actions */}
      {(action || secondaryAction) && (
        <div
          style={{
            display: 'flex',
            gap: '12px',
            flexWrap: 'wrap',
            justifyContent: 'center',
          }}
        >
          {action && (
            <button
              onClick={action.onClick}
              style={{
                padding: '10px 20px',
                fontSize: '14px',
                fontWeight: '600',
                color: '#ffffff',
                backgroundColor: '#3b82f6',
                border: 'none',
                borderRadius: '8px',
                cursor: 'pointer',
                transition: 'all 0.2s ease',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = '#2563eb';
                e.currentTarget.style.transform = 'translateY(-1px)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = '#3b82f6';
                e.currentTarget.style.transform = 'translateY(0)';
              }}
            >
              {action.label}
            </button>
          )}

          {secondaryAction && (
            <button
              onClick={secondaryAction.onClick}
              style={{
                padding: '10px 20px',
                fontSize: '14px',
                fontWeight: '600',
                color: '#4b5563',
                backgroundColor: '#ffffff',
                border: '1px solid #d1d5db',
                borderRadius: '8px',
                cursor: 'pointer',
                transition: 'all 0.2s ease',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.borderColor = '#9ca3af';
                e.currentTarget.style.backgroundColor = '#f9fafb';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.borderColor = '#d1d5db';
                e.currentTarget.style.backgroundColor = '#ffffff';
              }}
            >
              {secondaryAction.label}
            </button>
          )}
        </div>
      )}
    </div>
  );
};

// mycelix-workspace/happs/lucid/ui/src/lib/components/ui/EmptyState.svelte
<!--
  Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
  SPDX-License-Identifier: AGPL-3.0-or-later
  Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
-->
<script lang="ts">
  /**
   * EmptyState - Display when no data is available
   *
   * Usage:
   * <EmptyState
   *   icon="search"
   *   title="No results found"
   *   description="Try adjusting your search terms"
   * />
   */

  export let icon: 'search' | 'inbox' | 'chart' | 'users' | 'lightbulb' | 'shield' | 'star' = 'inbox';
  export let title: string;
  export let description: string = '';
  export let actionLabel: string | undefined = undefined;
  export let onAction: (() => void) | undefined = undefined;

  const icons = {
    search: 'Search icon',
    inbox: 'Inbox icon',
    chart: 'Chart icon',
    users: 'Users icon',
    lightbulb: 'Lightbulb icon',
    shield: 'Shield icon',
    star: 'Star icon',
  };
</script>

<div class="empty-state">
  <div class="empty-icon">
    <span class="icon-placeholder">{icons[icon]}</span>
  </div>
  <h3 class="empty-title">{title}</h3>
  {#if description}
    <p class="empty-description">{description}</p>
  {/if}
  {#if actionLabel && onAction}
    <button class="empty-action" on:click={onAction}>
      {actionLabel}
    </button>
  {/if}
</div>

<style>
  .empty-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    padding: 40px 20px;
    min-height: 200px;
  }

  .empty-icon {
    width: 64px;
    height: 64px;
    border-radius: 16px;
    background: var(--bg-tertiary, #0f172a);
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 16px;
  }

  .icon-placeholder {
    font-size: 12px;
    color: var(--text-muted, #94a3b8);
    opacity: 0.5;
  }

  .empty-title {
    margin: 0 0 8px 0;
    font-size: 16px;
    font-weight: 600;
    color: var(--text-primary, #f8fafc);
  }

  .empty-description {
    margin: 0 0 20px 0;
    font-size: 13px;
    color: var(--text-muted, #94a3b8);
    max-width: 300px;
    line-height: 1.5;
  }

  .empty-action {
    padding: 10px 20px;
    background: var(--color-primary, #3b82f6);
    border: none;
    border-radius: 8px;
    color: white;
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
    transition: background 0.15s;
  }

  .empty-action:hover {
    background: var(--color-primary-hover, #2563eb);
  }
</style>
