// mycelix-edunet/apps/web/src/components/LoadingSkeleton.tsx
/**
 * LoadingSkeleton Component
 *
 * Animated skeleton loader for content that is being fetched
 */

import React from 'react';

interface LoadingSkeletonProps {
  width?: string;
  height?: string;
  borderRadius?: string;
  className?: string;
}

export const LoadingSkeleton: React.FC<LoadingSkeletonProps> = ({
  width = '100%',
  height = '20px',
  borderRadius = '4px',
  className,
}) => {
  return (
    <div
      className={className}
      style={{
        width,
        height,
        borderRadius,
        background: 'linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%)',
        backgroundSize: '200% 100%',
        animation: 'shimmer 1.5s infinite',
      }}
    >
      <style>
        {`
          @keyframes shimmer {
            0% {
              background-position: 200% 0;
            }
            100% {
              background-position: -200% 0;
            }
          }
        `}
      </style>
    </div>
  );
};

/**
 * LoadingCard - Skeleton for card layouts
 */
interface LoadingCardProps {
  height?: string;
}

export const LoadingCard: React.FC<LoadingCardProps> = ({ height }) => {
  return (
    <div
      style={{
        border: '1px solid #e5e7eb',
        borderRadius: '8px',
        padding: '20px',
        backgroundColor: '#ffffff',
        minHeight: height,
      }}
    >
      {/* Header */}
      <div style={{ marginBottom: '16px' }}>
        <LoadingSkeleton height="24px" width="70%" />
        <div style={{ marginTop: '8px' }}>
          <LoadingSkeleton height="16px" width="40%" />
        </div>
      </div>

      {/* Body */}
      <div style={{ marginBottom: '16px' }}>
        <LoadingSkeleton height="14px" width="100%" />
        <div style={{ marginTop: '8px' }}>
          <LoadingSkeleton height="14px" width="90%" />
        </div>
      </div>

      {/* Tags */}
      <div style={{ display: 'flex', gap: '8px', marginBottom: '16px' }}>
        <LoadingSkeleton height="24px" width="60px" borderRadius="12px" />
        <LoadingSkeleton height="24px" width="80px" borderRadius="12px" />
        <LoadingSkeleton height="24px" width="70px" borderRadius="12px" />
      </div>

      {/* Footer */}
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          paddingTop: '16px',
          borderTop: '1px solid #e5e7eb',
        }}
      >
        <LoadingSkeleton height="14px" width="100px" />
        <LoadingSkeleton height="14px" width="80px" />
      </div>
    </div>
  );
};

/**
 * LoadingSpinner - Circular spinner for inline loading
 */
export const LoadingSpinner: React.FC<{ size?: number; color?: string }> = ({
  size = 24,
  color = '#3b82f6',
}) => {
  return (
    <div
      style={{
        width: size,
        height: size,
        border: `3px solid #e5e7eb`,
        borderTop: `3px solid ${color}`,
        borderRadius: '50%',
        animation: 'spin 0.8s linear infinite',
      }}
    >
      <style>
        {`
          @keyframes spin {
            0% {
              transform: rotate(0deg);
            }
            100% {
              transform: rotate(360deg);
            }
          }
        `}
      </style>
    </div>
  );
};

/**
 * LoadingPage - Full page loading state
 */
export const LoadingPage: React.FC<{ message?: string }> = ({
  message = 'Loading...',
}) => {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '400px',
        gap: '16px',
      }}
    >
      <LoadingSpinner size={48} />
      <p style={{ color: '#6b7280', fontSize: '16px' }}>{message}</p>
    </div>
  );
};

// mycelix-workspace/happs/lucid/ui/src/lib/components/ui/LoadingSkeleton.svelte
<script lang="ts">
  /**
   * LoadingSkeleton - Animated placeholder for loading states
   *
   * Usage:
   * <LoadingSkeleton variant="text" />
   * <LoadingSkeleton variant="circle" size={40} />
   * <LoadingSkeleton variant="rect" width="100%" height={200} />
   */

  export let variant: 'text' | 'circle' | 'rect' | 'card' = 'text';
  export let width: string | number = '100%';
  export let height: string | number = variant === 'text' ? 16 : 100;
  export let size: number | undefined = undefined; // For circle variant
  export let lines: number = 1; // For text variant
  export let animated: boolean = true;

  $: computedWidth = typeof width === 'number' ? `${width}px` : width;
  $: computedHeight = typeof height === 'number' ? `${height}px` : height;
  $: circleSize = size ? `${size}px` : '40px';
</script>

{#if variant === 'text'}
  <div class="skeleton-text" class:animated>
    {#each Array(lines) as _, i}
      <div
        class="skeleton-line"
        style="width: {i === lines - 1 && lines > 1 ? '70%' : computedWidth}; height: {computedHeight}"
      ></div>
    {/each}
  </div>
{:else if variant === 'circle'}
  <div
    class="skeleton-circle"
    class:animated
    style="width: {circleSize}; height: {circleSize}"
  ></div>
{:else if variant === 'rect'}
  <div
    class="skeleton-rect"
    class:animated
    style="width: {computedWidth}; height: {computedHeight}"
  ></div>
{:else if variant === 'card'}
  <div class="skeleton-card" class:animated>
    <div class="skeleton-card-header">
      <div class="skeleton-circle" style="width: 40px; height: 40px"></div>
      <div class="skeleton-card-title">
        <div class="skeleton-line" style="width: 60%; height: 14px"></div>
        <div class="skeleton-line" style="width: 40%; height: 12px"></div>
      </div>
    </div>
    <div class="skeleton-card-body">
      <div class="skeleton-line" style="width: 100%; height: 12px"></div>
      <div class="skeleton-line" style="width: 100%; height: 12px"></div>
      <div class="skeleton-line" style="width: 80%; height: 12px"></div>
    </div>
  </div>
{/if}

<style>
  .skeleton-line,
  .skeleton-circle,
  .skeleton-rect,
  .skeleton-card {
    background: linear-gradient(
      90deg,
      var(--bg-tertiary, #0f172a) 25%,
      var(--bg-secondary, #1e293b) 50%,
      var(--bg-tertiary, #0f172a) 75%
    );
    background-size: 200% 100%;
    border-radius: 4px;
  }

  .animated {
    animation: shimmer 1.5s infinite;
  }

  @keyframes shimmer {
    0% {
      background-position: 200% 0;
    }
    100% {
      background-position: -200% 0;
    }
  }

  .skeleton-text {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .skeleton-line {
    border-radius: 4px;
  }

  .skeleton-circle {
    border-radius: 50%;
    flex-shrink: 0;
  }

  .skeleton-rect {
    border-radius: 8px;
  }

  .skeleton-card {
    padding: 16px;
    border-radius: 12px;
    background: var(--bg-secondary, #1e293b);
  }

  .skeleton-card-header {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-bottom: 16px;
  }

  .skeleton-card-title {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  .skeleton-card-body {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .skeleton-card .skeleton-line,
  .skeleton-card .skeleton-circle {
    background: linear-gradient(
      90deg,
      var(--bg-tertiary, #0f172a) 25%,
      rgba(148, 163, 184, 0.1) 50%,
      var(--bg-tertiary, #0f172a) 75%
    );
    background-size: 200% 100%;
  }

  .skeleton-card.animated .skeleton-line,
  .skeleton-card.animated .skeleton-circle {
    animation: shimmer 1.5s infinite;
  }
</style>
